// Define action types
export const ActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",

  // domain
  DOMAIN: "CHECK_DOMAIN",

  // branches
  GET_BRANCH: "FETCH_BRANCH",

   // deliveron
  GET_DELIVERON: "FETCH_DELIVERON",

  // orders
  GET_ORDERS: "FETCH_ORDERS",
  GET_ACCEPTED_ORDERS: "FETCH_ACCEPTED_ORDERS",
  GET_PRODUCTS: "FETCH_PRODUCTS",

  // order cart
  GET_ORDER_CART: "FETCH_ORDER_CART",

  // theme
  DARK_THEME: "DARK_THEME",
  LIGHT_THEME: "LIGHT_THEME",
};